<a href="https://colab.research.google.com/github/brayannmb/FCD-DSA/blob/main/FCD_Python_Pyspark.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Scientist Formation - Data Science Academy

##Module 01 - Numpy

* Manipulate data with Numpy can be faster than using Pandas.
* It is possible to use Numpy in distributed environments 

##01-Cap02-Numpy - Chapter 2 - Data Manipulation with Numpy

In [1]:
import numpy as np

In [2]:
# by default array method creates elements with integer data type

#Unidimensional array:
array1 = np.array([10, 20, 30, 40])
print(array1); print(array1.shape); print(array1.ndim)  #ndim: number of dimensions

[10 20 30 40]
(4,)
1


In [3]:
#Bi-dimensional array:
array2 = np.array([[10, 20, 30], [40, 50, 60]])
print(array2); print(array2.shape); print(array2.ndim)

[[10 20 30]
 [40 50 60]]
(2, 3)
2


In [4]:
#Arange method
array3 = np.arange(10); array3 #start: 0, end: 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#Defining start and end - this method is exclusive
array4 = np.arange(0, 20, 5); array4

array([ 0,  5, 10, 15])

In [6]:
#Numpy zeros method
array5 = np.zeros((10, 8)); array5

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
#Numpy ones method
array6 = np.ones((2, 3, 2)); array6 #2 rows, 3 columns and 2 dimensions

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [8]:
#Identity matrix - main diagonal is filled by number one 
array7 = np.eye(5); array7

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
#Main diagonal
array8 = np.diag((2, 3, 4, 5, 6)); array8

array([[2, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 6]])

In [10]:
#Random numeric values
np.random.seed(100) #set seed
array9= np.random.rand(5); array9

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [11]:
#Random numeric values (Gaussian Distribution)
array10 = np.random.randn(5); array10

array([ 0.35467445, -0.78606433, -0.2318722 ,  0.20797568,  0.93580797])

In [12]:
#Empty array
array11 = np.empty((3, 2)); array11

array([[3.0421266e-316, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000]])

In [13]:
#Numpy tile method
print(np.array([[9, 4], [3, 7]]))
print()
print(np.tile(np.array([[9, 4], [3, 7]]), 4))
print()
print(np.tile(np.array([[9, 4], [3, 7]]), (2, 2)))

[[9 4]
 [3 7]]

[[9 4 9 4 9 4 9 4]
 [3 7 3 7 3 7 3 7]]

[[9 4 9 4]
 [3 7 3 7]
 [9 4 9 4]
 [3 7 3 7]]


In [14]:
#Numpy data types
array12 = np.array([8, -3, 5, 9], dtype='float'); print(array12); print(array12.dtype)

[ 8. -3.  5.  9.]
float64


In [15]:
#String array
array13 = np.array(['Data', 'Scientist', 'Formation - DSA']); array13

array(['Data', 'Scientist', 'Formation - DSA'], dtype='<U15')

In [17]:
#Boolean array
array14 = np.array([True, False, True]); array14

array([ True, False,  True])

In [19]:
#Convert data type
array15 = np.array([5.55, -3.8, 2]).astype(int); print(array15.dtype); print(array15)

int64
[ 5 -3  2]
